config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  authenticated :user do
    root 'groups#index', as: :authenticated_root
  end

  root "splash#index"

  resources :users, only: [:index] do
    resources :groups, only: [:index, :new, :create, :edit, :update, :destroy] do
      resources :expenses, only: [:index, :new, :create, :edit, :update, :destroy]
    end
  end

  resources :splash, only: [:index]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Expense, public: true

    return unless user.present?

    can :manage, Expense, author_id: user.id
    can :manage, Group, author_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :groups, through: :group_expenses
  has_many :group_expenses, dependent: :destroy

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :author_id, presence: true
  validates :group_id, presence: true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :expenses, through: :group_expenses
  has_many :group_expenses, dependent: :destroy

  validates :name, presence: true
  validates :icon, presence: true
  validates :author_id, presence: true
end

app/models/group_expense.rb
class GroupExpense < ApplicationRecord
  belongs_to :group
  belongs_to :expense

  validates :group_id, presence: true
  validates :expense_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :groups, dependent: :destroy, foreign_key: 'author_id'
  has_many :expenses, dependent: :destroy, foreign_key: 'author_id'

  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @group = @user.groups.find(params[:group_id])
    @expenses = @user.expenses.where(group_id: @group.id)
    @total_transactions = total_transactions
    redirect_to user_group_expenses_path(current_user) unless User.find_by(id: params[:user_id]) == current_user
  end

  def new
    @user = current_user
    @expense = Expense.new
    @group = @user.groups.find(params[:group_id])
  end

  def create
    @user = current_user
    @group = @user.groups.find_by(id: expense_params[:group_id])
    @expense = @user.expenses.create(name: expense_params[:name], amount: expense_params[:amount], author_id: @user.id,
                                     group_id: expense_params[:group_id])
    @group_expense = @expense.group_expenses.new(group_id: @group.id, expense_id: @expense.id)
    if @expense.save && @group_expense.save
      flash[:notice] = 'Transaction successfully created!'
      redirect_to user_group_expenses_path(current_user, @group)
    else
      flash[:notice] = 'Transaction not created!'
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @user = current_user
    @group = @user.groups.find(params[:group_id])
    @expense = @user.expenses.find(params[:id])
    @expense.destroy
    flash[:notice] = 'Transaction successfully deleted!'
    redirect_to user_group_expenses_path(current_user, @group)
  end

  def edit
    @user = current_user
    @group = @user.groups.find(params[:group_id])
    @expense = @user.expenses.find(params[:id])
  end

  def update
    @user = current_user
    @group = @user.groups.find(params[:group_id])
    @expense = @user.expenses.find(params[:id])
    if @expense.update(expense_params)
      flash[:notice] = 'Transaction successfully updated!'
      redirect_to user_group_expenses_path(current_user, @group)
    else
      flash[:notice] = 'Transaction not updated!'
      render :edit, status: :unprocessable_entity
    end
  end

  def total_transactions
    @user = current_user
    @group = @user.groups.find(params[:group_id])
    @expenses = @user.expenses.where(group_id: @group.id)
    @total_transactions = 0
    @expenses.each do |expense|
      @total_transactions += expense.amount
    end
    @total_transactions
  end

  private

  def expense_params
    params.require(:expense).permit(:name, :amount, :group_id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  def index
    @user = current_user
    @groups = @user.groups
    redirect_to user_groups_path(current_user) unless User.find_by(id: params[:user_id]) == current_user
  end

  def new
    @group = Group.new
  end

  def create
    @user = current_user
    @group = @user.groups.new(group_params)
    @group.author_id = @user.id
    if @group.save
      flash[:notice] = 'Group successfully created!'
      redirect_to user_groups_path(current_user)
    else
      flash[:notice] = 'Group not created!'
      render :new
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    flash[:notice] = 'Group successfully deleted!'
    redirect_to user_groups_path(current_user)
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      flash[:notice] = 'Group successfully updated!'
      redirect_to user_groups_path(current_user)
    else
      flash[:notice] = 'Group not updated!'
      render :edit
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/expenses/edit.html.erb
<div class="form_container">
<%= form_for @expense, url: user_group_expense_path, method: :put, class: "form" do |form| %>
  <div>
  <br>
  </div>
  <div class="form-row">
  <%= form.text_field :name, class: "text_field2" %>
  </div>
   <div class="form-row">
   <%= form.number_field :amount, in: 0.00..100000000.00, step: 0.10, class: "text_field2" %>
  </div>
  <div class="form-row">
    <% @groups = Group.all %>
     <%= form.select(:group_id, @groups.map { |group| [group.name, group.id] }, {:class => "custom-select"}) %>
  </div>
  <div class="submit_button_container">
    <%= form.submit "Update", class: "button submit" %>
  </div>
<% end %>
</div>

app/views/expenses/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Moneypenny App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "group", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="group-container2">
  <div class="group-data">
    <p>Total Amount: </p>
  </div>
  <div class="group-sum">
    <h3>$<%= @total_transactions %></h3>
  </div>
</div>
   <% @expenses.order(created_at: :desc).each do |expense| %>
    <%= render "partials/expense_card", expense: expense, group: expense.group_id  %>
    <% end %>
   <div class="btn-container">
    <%= link_to new_user_group_expense_path(current_user, @group), {:class => "links-btn"} do%>
      <button class="button bottom-btn">New Transaction</button>
    <%end%>
      </div>
  </body>
</html>

app/views/expenses/new.html.erb
<div class="form_container">
<%= form_with model: @expense, url: user_group_expenses_url, method: :post, class: "form",local: true, data: { turbo: false } do |form| %>
  <div>
  <br>
  </div>
  <div class="form-row">
  <%= form.text_field :name, placeholder: "Add Name", required: true, class: "text_field2" %>
  </div>
   <div class="form-row">
   <%= form.number_field :amount, in: 0.00..100000000.00, step: 0.10, required: true, class: "text_field2" %>
  </div>
  <div class="form-row">
    <% @groups = @user.groups %>
     <%= form.select(:group_id, @groups.map { |group| [group.name, group.id] }, {:include_blank => "-- Select --"}, {:class => "custom-select"}) %>
  </div>
  <div class="submit_button_container">
    <%= form.submit "Add", class: "button submit" %>
  </div>
<% end %>
</div>

app/views/groups/edit.html.erb
<div class="form_container">
<%= form_for @group, url: user_group_path, method: :put, class: "form" do |form| %>
  <div>
  <br>
  </div>
  <div class="form-row">
  <%= form.text_field :name, class: "text_field2" %>
  </div>
  <div class="form-row">
    <%= form.select :icon, ['noto:house-with-garden', 'emojione-v1:bus', 'emojione:pot-of-food', 'healthicons:electricity', 'map:insurance-agency', 'noto:health-worker-medium-light-skin-tone', 'logos:netflix-icon', 'flat-color-icons:debt', 'icon-park-solid:other'], class: "custom-select" %>
  </div>
  <div class="submit_button_container">
    <%= form.submit "Update", class: "button submit" %>
  </div>
  <div class="submit_button_container">
    <%= button_to 'Delete', user_group_path(current_user, @group), method: :delete, class: "button-delete submit" %>
  </div>
<% end %>
</div>

app/views/groups/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Moneypenny App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "group", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% @groups.each do |group| %>
        <%= render "partials/category_card", group: group %>
    <% end %>
    <div class="btn-container">
    <%= link_to new_user_group_path(current_user), {:class => "links-btn"} do%>
      <button class="button bottom-btn">New group</button>
    <%end%>
      </div>
  </body>
</html>

app/views/groups/new.html.erb
<div class="form_container">
<%= form_with model: @group, url: user_groups_path, method: :post, class: "form" do |form| %>
  <div>
  <br>
  </div>
  <div class="form-row">
  <%= form.text_field :name, placeholder: "Add Name", required: true, class: "text_field2" %>
  </div>
  <div class="form-row">
    <%# <% @icon = Group.all %>
    <%= form.select :icon, ['noto:house-with-garden', 'emojione-v1:bus', 'emojione:pot-of-food', 'healthicons:electricity', 'map:insurance-agency', 'noto:health-worker-medium-light-skin-tone', 'logos:netflix-icon', 'flat-color-icons:debt', 'icon-park-solid:other'], {:include_blank => "-- Select --"}, required: true, class: "custom-select" %>
     <%# <%= form.select(:icon, @icon.map { |icon| [icon.icon] }, {:include_blank => "-- Select --", :class => "custom-select" %>
  </div>
  <div class="submit_button_container">
    <%= form.submit "Add", class: "button submit" %>
  </div>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoneypennyApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://code.iconify.design/2/2.2.1/iconify.min.js"></script>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= render "partials/navbar_guest" %>
    <% end %>

      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/partials/_category_card.html.erb
<div class="group-container">
  <div class="group-data">
    <span class="iconify" data-icon="<%= group.icon %>" data-width="60" data-height="60"></span>
  </div>
  <div class="group-sum">
  <%= link_to user_group_expenses_path(current_user, group), {:class => "links"} do%>
  <p><%= group.name %></p>
  <%end%>
  </div>
  <div class="group-sum">
  <%= link_to edit_user_group_path(current_user, group), {:class => "links-btn"} do%>
      <button class="button-edit">Edit</button>
    <%end%>
  </div>
  
</div>

app/views/partials/_expense_card.html.erb
<div class="group-container">
  <div class="group-data2">
  <%= link_to edit_user_group_expense_path(current_user, expense.group_id, expense), {:class => "links-transaction"} do%>
    <p><%= expense.name %></p>
  <%end%>
    <%= button_to 'Delete', user_group_expense_path(current_user, group, expense), method: :delete, class: "button-delete"%>
  </div>
  <div class="group-sum">
    <h3>$<%= expense.amount %></h3>
  </div>
</div>

app/views/partials/_navbar_guest.html.erb
<nav class="nav-bar">
            <ul class="list">

              <% if @group && @group.id && current_page?(new_user_group_expense_path(current_user, @group))%>
                 <li class="item"><a href="<%= user_group_expenses_path(current_user, @group) %>"><span class="iconify" data-icon="akar-icons:arrow-left"></span></a></li>
                  <li class="item">CREATE TRANSACTION</li>
                   <li class="item"></li>
               <% end %>

               <% if current_page?(user_groups_path(current_user))%>
                  <li class="item"><a href="<%= root_path %>"><span class="iconify" data-icon="ant-design:menu-outlined"></span></a></li>
                  <li class="item">GROUPS</li>
                  <li class="item"><a class="nav-link" href="#"><%= link_to destroy_user_session_path, method: :delete, class: 'link' do%>
                  <span class="iconify" data-icon="ri:logout-box-r-line"></span>
                  <%end%>
                  </a></li>
               <% end %>
                  
               <% if @group != nil && current_page?(new_user_group_path(current_user))%>
                 <li class="item"><a href="<%= root_path %>"><span class="iconify" data-icon="akar-icons:arrow-left"></span></a></li>
                  <li class="item">CREATE GROUP</li>
                   <li class="item"></li>
               <% end %>

                   <% if @group != nil && @group.id != nil && current_page?(user_group_expenses_path(current_user, @group))%>
                 <li class="item"><a href="<%= root_path %>"><span class="iconify" data-icon="akar-icons:arrow-left"></span></a></li>
                  <li class="item">TRANSACTIONS</li>
                   <li class="item"></li>
               <% end %>

                <% if @group && @group.id && @expense && @expense.id && current_page?(edit_user_group_expense_path(current_user, @group, @expense))%>
                 <li class="item"><a href="<%= user_group_expenses_path(current_user, @group) %>"><span class="iconify" data-icon="akar-icons:arrow-left"></span></a></li>
                  <li class="item">EDIT TRANSACTION</li>
                   <li class="item"></li>
               <% end %>

 <% if @group && @group.id && current_page?(edit_user_group_path(current_user, @group))%>
                 <li class="item"><a href="<%= user_groups_path(current_user) %>"><span class="iconify" data-icon="akar-icons:arrow-left"></span></a></li>
                  <li class="item">EDIT GROUP</li>
                   <li class="item"></li>
               <% end %>
            


            </ul>

            

</nav>

app/views/splash/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Moneypenny App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "splash", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="splash-title">
    <%# <h1>Accountability</h1> %>
    <%= image_tag "app-icon.png", class:"app_icon" %>
  </div>
  <div class="splash-container">
    <%= link_to "LOG IN", new_user_session_path, class: 'login-btn' %>  
    <%= link_to "SIGN UP", new_user_registration_path, class: 'signup-btn' %>
  </div>
  </body>
</html>